[#ftl]
[#-- @implicitly included --]
[#-- @ftlvariable name="users" type="ru.itmo.web.lesson4.model.User[]" --]
[#-- @ftlvariable name="user" type="ru.itmo.web.lesson4.model.User" --]
[#-- @ftlvariable name="URI" type="java.lang.String" --]
[#-- @ftlvariable name="posts" type="ru.itmo.web.lesson4.model.Post[]" --]
